name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies (fix conflict)
        run: npm install --legacy-peer-deps

      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: Login to Expo
        run: eas login --token ${{ secrets.EXPO_TOKEN }}

      - name: Build APK
        run: eas build --platform android --profile preview --non-interactive
